#pragma config(Sensor, S3,     colour,         sensorEV3_Color)
#pragma config(Motor,  motorA,          x_motor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          y_motor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          z_motor,    tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void HexToBinStr(unsigned char* hexStr, unsigned char* binStr, int lenHex)
{
    memset(binStr, '0', lenHex * 8);
    unsigned char hexChar[2];
    for(int i = 0; i < lenHex; i++)
    {
        hexChar[0] = (hexStr[i] & 0xF0) >> 4;
        hexChar[1] = hexStr[i] & 0x0F;
        for(int j = 0; j < 2; j++)
        {
            for(int k = 0; k < 4; k++)
            {
                if(hexChar[j] & (0x08 >> k))
                {
                    binStr[8 * i + 4 * j + k] = '1';
                }
            }
        }
    }
}


task main()
{
	unsigned char bin1[257];
    unsigned char bin2[257];
    unsigned char bin3[257];
    unsigned char bin4[257];
	int i,j,p,q;
	unsigned char bits1[16]=
	{
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x20,0x00,
0x00,0x00,0x30,0x00,0x00,0x00,0x30,0x00,0x00,0x02,0x20,0x00,0x1F,0xFF,0x60,0x00,
	};
    unsigned char bits2[16]=
    {
    0x00,0x60,0x60,0x40,0x00,0x60,0x7F,0xE0,0x00,0x60,0x41,0x80,0x00,0x60,0xC1,0x00,
0x06,0x60,0xC1,0x00,0x06,0x60,0xC1,0x00,0x06,0x7F,0x23,0x00,0x06,0x61,0x23,0x00,
    };
    unsigned char bits3[16]=
    {
   0x06,0x62,0x23,0x00,0x06,0x60,0x22,0x00,0x06,0x60,0x16,0x00,0x06,0x60,0x16,0x00,
0x06,0x60,0x0C,0x00,0x06,0x67,0x0C,0x00,0x06,0x78,0x1C,0x00,0x07,0xC0,0x26,0x00,
    };
    unsigned char bits4[16]=
    {
  0x1E,0x00,0xC3,0x80,0x08,0x01,0x81,0xE0,0x00,0x06,0x00,0xE0,0x00,0x18,0x00,0x00,
0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    };

    
	HexToBinStr(bits, bin1, 32);
    HexToBinStr(bits, bin2, 32);
    HexToBinStr(bits, bin3, 32);
    HexToBinStr(bits, bin4, 32);

    while(true)
    {
        for(i=0;i<256;i++)
        {
            if(i%32==0&&i!=0)
            {
                resetMotorEncoder(y_motor);
                setMotorTarget(y_motor, 9, 50);
                waitUntilMotorStop(y_motor);
                resetMotorEncoder(x_motor);
                setMotorTarget(x_motor, 15*16, -50);
                waitUntilMotorStop(x_motor);
            }
            if(bin[i]=='1')
            {
                resetMotorEncoder(z_motor);
                setMotorTarget(z_motor, 90, 50);
                waitUntilMotorStop(z_motor);
                resetMotorEncoder(z_motor);
                setMotorTarget(z_motor, 90, -50);
                waitUntilMotorStop(z_motor);
                sleep(200);
            }
            resetMotorEncoder(x_motor);
            setMotorTarget(x_motor, 15, 50);
            waitUntilMotorStop(x_motor);
        }
        resetMotorEncoder(y_motor);
        setMotorTarget(y_motor, 9, 50);
        waitUntilMotorStop(y_motor);
        resetMotorEncoder(x_motor);
        setMotorTarget(x_motor, 15*16, -50);
        waitUntilMotorStop(x_motor);
        for(j=0;j<256;j++)
        {
            if(j%32==0&&j!=0)
            {
                resetMotorEncoder(y_motor);
                setMotorTarget(y_motor, 9, 50);
                waitUntilMotorStop(y_motor);
                resetMotorEncoder(x_motor);
                setMotorTarget(x_motor, 15*16, -50);
                waitUntilMotorStop(x_motor);
            }
            if(bin[j]=='1')
            {
                resetMotorEncoder(z_motor);
                setMotorTarget(z_motor, 90, 50);
                waitUntilMotorStop(z_motor);
                resetMotorEncoder(z_motor);
                setMotorTarget(z_motor, 90, -50);
                waitUntilMotorStop(z_motor);
                sleep(200);
            }
            resetMotorEncoder(x_motor);
            setMotorTarget(x_motor, 15, 50);
            waitUntilMotorStop(x_motor);
        }
        resetMotorEncoder(y_motor);
        setMotorTarget(y_motor, 9, 50);
        waitUntilMotorStop(y_motor);
        resetMotorEncoder(x_motor);
        setMotorTarget(x_motor, 15*16, -50);
        waitUntilMotorStop(x_motor);
        for(p=0;p<256;p++)
        {
            if(p%32==0&&p!=0)
            {
                resetMotorEncoder(y_motor);
                setMotorTarget(y_motor, 9, 50);
                waitUntilMotorStop(y_motor);
                resetMotorEncoder(x_motor);
                setMotorTarget(x_motor, 15*16, -50);
                waitUntilMotorStop(x_motor);
            }
            if(bin[p]=='1')
            {
                resetMotorEncoder(z_motor);
                setMotorTarget(z_motor, 90, 50);
                waitUntilMotorStop(z_motor);
                resetMotorEncoder(z_motor);
                setMotorTarget(z_motor, 90, -50);
                waitUntilMotorStop(z_motor);
                sleep(200);
            }
            resetMotorEncoder(x_motor);
            setMotorTarget(x_motor, 15, 50);
            waitUntilMotorStop(x_motor);
        }
        resetMotorEncoder(y_motor);
        setMotorTarget(y_motor, 9, 50);
        waitUntilMotorStop(y_motor);
        resetMotorEncoder(x_motor);
        setMotorTarget(x_motor, 15*16, -50);
        waitUntilMotorStop(x_motor);
        for(q=0;q<256;q++)
        {
            if(q%32==0&&q!=0)
            {
                resetMotorEncoder(y_motor);
                setMotorTarget(y_motor, 9, 50);
                waitUntilMotorStop(y_motor);
                resetMotorEncoder(x_motor);
                setMotorTarget(x_motor, 15*16, -50);
                waitUntilMotorStop(x_motor);
            }
            if(bin[1]=='1')
            {
                resetMotorEncoder(z_motor);
                setMotorTarget(z_motor, 90, 50);
                waitUntilMotorStop(z_motor);
                resetMotorEncoder(z_motor);
                setMotorTarget(z_motor, 90, -50);
                waitUntilMotorStop(z_motor);
                sleep(200);
            }
            resetMotorEncoder(x_motor);
            setMotorTarget(x_motor, 15, 50);
            waitUntilMotorStop(x_motor);
        }
        if(q==256)
        {
            break;
        }
    }
}
